services:

  - type: web
    name: myaccess-user-service
    runtime: docker
    dockerfilePath: ./Backend/user-service/Dockerfile
    dockerContext: ./Backend/user-service
    envVars:
      - key: PORT
        value: 9091
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: 600000
      - key: JWT_REFRESH_EXPIRATION
        value: 600000
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false

  - type: web
    name: myaccess-card-service
    runtime: docker
    dockerfilePath: ./Backend/card-service/Dockerfile
    dockerContext: ./Backend/card-service
    envVars:
      - key: PORT
        value: 9092
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false

  - type: web
    name: myaccess-news-service
    runtime: docker
    dockerfilePath: ./Backend/news-service/Dockerfile
    dockerContext: ./Backend/news-service
    envVars:
      - key: PORT
        value: 9093
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false

  - type: web
    name: myaccess-notifications-service
    runtime: docker
    dockerfilePath: ./Backend/notifications-service/Dockerfile
    dockerContext: ./Backend/notifications-service
    envVars:
      - key: PORT
        value: 9094
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false

  - type: web
    name: myaccess-gateway
    runtime: docker
    dockerfilePath: ./Backend/api-gateway/Dockerfile
    dockerContext: ./Backend/api-gateway
    envVars:
      - key: PORT
        value: 8080
      - key: JWT_SECRET
        sync: false
      - key: BACKEND_URI
        sync: false
