services:

  - type: web
    name: myaccess-user-service
    runtime: docker
    dockerfilePath: ./Backend/user-service/Dockerfile
    dockerContext: ./Backend/user-service
    envVars:
      - key: PORT
        value: 10000
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: 600000
      - key: JWT_REFRESH_EXPIRATION
        value: 600000
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false

  - type: web
    name: myaccess-card-service
    runtime: docker
    dockerfilePath: ./Backend/card-service/Dockerfile
    dockerContext: ./Backend/card-service
    envVars:
      - key: PORT
        value: 10000
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false

  - type: web
    name: myaccess-news-service
    runtime: docker
    dockerfilePath: ./Backend/news-service/Dockerfile
    dockerContext: ./Backend/news-service
    envVars:
      - key: PORT
        value: 10000
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false

  - type: web
    name: myaccess-notifications-service
    runtime: docker
    dockerfilePath: ./Backend/notifications-service/Dockerfile
    dockerContext: ./Backend/notifications-service
    envVars:
      - key: PORT
        value: 10000
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false

  - type: web
    name: myaccess-gateway
    runtime: docker
    dockerfilePath: ./Backend/api-gateway/Dockerfile
    dockerContext: ./Backend/api-gateway
    envVars:
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: AUTH_SERVICE_URI
        value: https://myaccess-auth-pzen.onrender.com
      - key: USER_SERVICE_URI
        value: https://myaccess-user.onrender.com
      - key: CARD_SERVICE_URI
        value: https://myaccess-card-a4e6.onrender.com
      - key: NEWS_SERVICE_URI
        value: https://myaccess-news-poqo.onrender.com
      - key: NOTIFICATIONS_SERVICE_URI
        value: https://myaccess-notification-mjsk.onrender.com
