services:
  - type: web
    name: api-gateway
    runtime: docker
    rootDir: api-gateway
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: SERVER_PORT
        value: 10000
      - key: AUTH_SERVICE_URI
        value: https://myaccess-auth-pzen.onrender.com
      - key: USER_SERVICE_URI
        value: https://myaccess-user.onrender.com
      - key: CARD_SERVICE_URI
        value: https://myaccess-card-a4e6.onrender.com
      - key: NEWS_SERVICE_URI
        value: https://myaccess-news-poqo.onrender.com
      - key: NOTIFICATIONS_SERVICE_URI
        value: https://myaccess-notification-mjsk.onrender.com
      - key: JWT_SECRET
        sync: false
  - type: web
    name: user-service
    runtime: docker
    rootDir: user-service
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: SERVER_PORT
        value: 10000
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
  - type: web
    name: auth-service
    runtime: docker
    rootDir: auth-service
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: SERVER_PORT
        value: 10000
  - type: web
    name: card-service
    runtime: docker
    rootDir: card-service
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: SERVER_PORT
        value: 10000
  - type: web
    name: news-service
    runtime: docker
    rootDir: news-service
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: SERVER_PORT
        value: 10000
      - key: NEWS_DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
  - type: web
    name: notifications-service
    runtime: docker
    rootDir: notifications-service
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: SERVER_PORT
        value: 10000
