server:
  port: ${SERVER_PORT:9090}

spring:
  application:
    name: myaccess

  datasource:
    user-service:
      jdbc-url: jdbc:mysql://${DB_HOST}:${DB_PORT}/user_service
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
    auth-service:
      jdbc-url: jdbc:mysql://${DB_HOST}:${DB_PORT}/auth_service
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
    card-service:
      jdbc-url: jdbc:mysql://${DB_HOST}:${DB_PORT}/card_service
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
    news-service:
      jdbc-url: jdbc:mysql://${DB_HOST}:${DB_PORT}/news_service
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
    notifications-service:
      jdbc-url: jdbc:mysql://${DB_HOST}:${DB_PORT}/notifications_service
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

security:
  jwt:
    secret-key: ${JWT_SECRET}
    tokenExpiration: ${JWT_EXPIRATION}
