import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#EAE6E6' },
  contentFrame: { flex: 1, flexDirection: 'row' },
  mainArea: { flex: 1 },
  mainScroll: { flexGrow: 1, paddingTop: 6, paddingBottom: 24 },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(17, 24, 39, 0.54)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
  },
  modalPanel: {
    width: '100%',
    maxWidth: 380,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    padding: 14,
    gap: 12,
  },
  modalHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  modalTitleBlock: { flex: 1 },
  modalTitle: { fontSize: 15, fontWeight: '900', color: '#111827' },
  modalSubtitle: { fontSize: 12, fontWeight: '700', color: '#6B7280', marginTop: 2 },
  closeBtn: { paddingHorizontal: 12, paddingVertical: 7, borderRadius: 8, backgroundColor: '#F3F4F6' },
  closeBtnText: { fontSize: 12, fontWeight: '800', color: '#374151' },
  singlePrintArea: { alignItems: 'center', paddingVertical: 8 },
  modalActions: { alignItems: 'flex-end' },
  verticalCarnet: {
    width: 265,
    height: 390,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#D0D0D0',
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  verticalTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    height: 150,
  },
  verticalLogoBox: { width: 72, paddingTop: 2, alignItems: 'flex-start' },
  verticalLogo: { width: 70, height: 70 },
  verticalPhotoFrame: {
    width: 118,
    height: 148,
    overflow: 'hidden',
    backgroundColor: '#E5E7EB',
  },
  verticalPhoto: { width: '100%', height: '100%' },
  verticalBody: { flex: 1 },
  verticalRole: {
    fontSize: 12,
    color: '#000000',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    fontWeight: '400',
    lineHeight: 14,
    marginBottom: 3,
  },
  verticalGreenRule: {
    height: 3,
    backgroundColor: '#008542',
    marginBottom: 10,
  },
  verticalBrand: {
    fontSize: 19,
    lineHeight: 22,
    fontWeight: '700',
    color: '#008542',
    marginBottom: 5,
  },
  verticalIdentity: { fontSize: 11, fontWeight: '400', color: '#000000', marginBottom: 8 },
  verticalBarcodeWrap: {
    height: 28,
    whidth: 6,
    flexDirection: 'row',
    alignItems: 'flex-end',
    marginBottom: 12,
    marginRight:12,
  },
  verticalBarcodeBar: { height: 26, backgroundColor: '#000000' },
  verticalFooter: { gap: 0, paddingBottom: 2 },
  verticalRegional: { color: '#000000', fontSize: 12, fontWeight: '700', lineHeight: 15 },
  verticalCenter: { color: '#008542', fontSize: 12, fontWeight: '600', lineHeight: 14, marginTop: 3 },
  verticalMuted: { color: '#000000', fontSize: 12, fontWeight: '400', lineHeight: 13, marginTop: 3 },
  verticalMutedLast: { color: '#000000', fontSize: 12, fontWeight: '400', lineHeight: 13, marginTop: 2 },
  verticalCarnetBack: { backgroundColor: '#FFFFFF', justifyContent: 'space-between' },
  verticalBackText: { fontSize: 10.5, color: '#374151', lineHeight: 13, fontWeight: '500', textAlign: 'left' },
  verticalSignatureImage: { width: 200, height: 70, marginBottom: 3, resizeMode: 'contain' },
  verticalSignatureLabel: { fontSize: 10, textAlign: 'center', fontWeight: '800', letterSpacing: 0.4 },
  flipHint: { fontSize: 11, color: '#6B7280', fontWeight: '600' },
  headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 14, flexWrap: 'wrap', gap: 10 },
  pageTitle: { fontSize: 18, fontWeight: '800', color: '#151515', marginBottom: 2 },
  pageSubtitle: { fontSize: 12, color: '#2C2C2C', maxWidth: 400 },
  headerActions: { flexDirection: 'row', gap: 8 },
  backBtn: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 8, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#D1D5DB' },
  backBtnText: { fontSize: 12, color: '#374151', fontWeight: '600' },
  printBtn: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 8, backgroundColor: '#079B72' },
  printBtnDisabled: { backgroundColor: '#9CA3AF' },
  printBtnText: { fontSize: 12, color: '#FFFFFF', fontWeight: '700' },
  fichaTabsRow: { marginBottom: 8, maxHeight: 32 },
  fichaTabsContent: { gap: 8, paddingRight: 4 },
  fichaTab: {
    width: 82,
    height: 30,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#C7D7D0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fichaTabActive: { backgroundColor: '#087C4A', borderColor: '#087C4A' },
  fichaTabText: { fontSize: 12, lineHeight: 14, fontWeight: '800', color: '#3F4A45', textAlign: 'center' },
  fichaTabTextActive: { color: '#FFFFFF' },
  fichaInfo: { marginBottom: 10 },
  fichaInfoTitle: { fontSize: 15, fontWeight: '900', color: '#1F2937' },
  fichaInfoSub: { fontSize: 12, color: '#6B7280', marginTop: 2 },
  carnetGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 16 },
  fichaPrintGroup: { width: '100%', marginBottom: 18 },
  fichaPrintTitle: { fontSize: 14, fontWeight: '900', color: '#087C4A', marginBottom: 10 },
  emptyText: { color: '#9CA3AF', fontSize: 13, padding: 20 },
  carnetCard: {
    width: 300,
    borderRadius: 14,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.14,
    shadowRadius: 10,
    elevation: 6,
    backgroundColor: '#FFFFFF',
  },
  carnetHeader: { backgroundColor: '#079B72', flexDirection: 'row', alignItems: 'center', padding: 10, gap: 8 },
  carnetLogoBox: { width: 32, height: 32, borderRadius: 6, backgroundColor: '#FFFFFF', justifyContent: 'center', alignItems: 'center' },
  carnetLogoText: { fontSize: 9, fontWeight: '900', color: '#079B72' },
  carnetInstitution: { fontSize: 10, fontWeight: '800', color: '#FFFFFF' },
  carnetSubtitle: { fontSize: 8, color: '#D1FAE5' },
  carnetBody: { flexDirection: 'row', padding: 10, gap: 10 },
  carnetPhotoBox: {
    width: 74,
    height: 92,
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: '#E5E7EB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  carnetPhoto: { width: '100%', height: '100%' },
  carnetPhotoPlaceholder: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#D1FAE5',
  },
  carnetPhotoInitial: { fontSize: 28, fontWeight: '900', color: '#047857' },
  carnetData: { flex: 1, gap: 4 },
  carnetName: { fontSize: 13, fontWeight: '800', color: '#111827' },
  roleBadge: { alignSelf: 'flex-start', backgroundColor: '#E8FFF5', borderRadius: 999, paddingHorizontal: 8, paddingVertical: 3 },
  roleBadgeText: { fontSize: 9, fontWeight: '800', color: '#047857' },
  carnetFieldRow: { flexDirection: 'row', alignItems: 'center' },
  carnetFieldLabel: { fontSize: 9, fontWeight: '800', color: '#4B5563' },
  carnetFieldValue: { flex: 1, fontSize: 9, color: '#111827' },
  carnetFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
    paddingHorizontal: 10,
    paddingBottom: 10,
  },
  carnetFooterText: { fontSize: 8, color: '#6B7280', fontWeight: '700' },
  warningBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FEF3C7',
    borderLeftWidth: 4,
    borderLeftColor: '#F59E0B',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginTop: 10,
    marginBottom: 14,
    gap: 10,
  },
  warningIcon: {
    fontSize: 15,
  },
  warningText: {
    flex: 1,
    color: '#B45309',
    fontSize: 13,
    fontWeight: '600',
  },
  warningClose: {
    paddingHorizontal: 6,
  },
  warningCloseText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#B45309',
  },
});
