import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#EAE6E6' },
  contentFrame: { flex: 1, flexDirection: 'row' },
  mainArea: { flex: 1 },
  mainScroll: { flexGrow: 1, paddingTop: 6, paddingBottom: 24 },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(17, 24, 39, 0.54)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
  },
  modalPanel: {
    width: '100%',
    maxWidth: 380,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    padding: 14,
    gap: 12,
  },
  modalHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  modalTitleBlock: { flex: 1 },
  modalTitle: { fontSize: 15, fontWeight: '900', color: '#111827' },
  modalSubtitle: { fontSize: 12, fontWeight: '700', color: '#6B7280', marginTop: 2 },
  closeBtn: { paddingHorizontal: 12, paddingVertical: 7, borderRadius: 8, backgroundColor: '#F3F4F6' },
  closeBtnText: { fontSize: 12, fontWeight: '800', color: '#374151' },
  singlePrintArea: { alignItems: 'center', paddingVertical: 8 },
  modalActions: { alignItems: 'flex-end' },
  verticalCarnet: {
    width: 265,
    height: 420,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D7D7D7',
    backgroundColor: '#FDFDFD',
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 12,
    justifyContent: 'space-between',
  },
  verticalTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  verticalLogoBox: { width: 88, alignItems: 'center', marginTop: 2 },
  verticalLogo: { width: 80, height: 80 },
  verticalPhotoFrame: {
    width: 122,
    height: 152,
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: '#E9E9E9',
  },
  verticalPhoto: { width: '100%', height: '100%' },
  verticalBody: { marginTop: 10 },
  verticalRole: {
    fontSize: 14,
    color: '#2F2F2F',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  verticalGreenRule: {
    height: 4,
    backgroundColor: '#0A8A4A',
    borderRadius: 2,
    marginBottom: 8,
  },
  verticalBrand: {
    fontSize: 17,
    lineHeight: 21,
    fontWeight: '900',
    color: '#118449',
    marginBottom: 6,
  },
  verticalIdentity: { fontSize: 10, color: '#3A3A3A', marginBottom: 10 },
  verticalBarcodeWrap: {
    height: 34,
    flexDirection: 'row',
    alignItems: 'flex-end',
    marginBottom: 10,
  },
  verticalBarcodeBar: { height: 28, backgroundColor: '#111111' },
  verticalFooter: { gap: 2 },
  verticalRegional: { color: '#555555', fontSize: 13, fontWeight: '900' },
  verticalCenter: { color: '#118449', fontSize: 11, fontWeight: '800' },
  verticalMuted: { color: '#4A4A4A', fontSize: 10 },
  verticalCarnetBack: { backgroundColor: '#FFFFFF', justifyContent: 'space-between' },
  verticalBackText: { fontSize: 10, color: '#2E2E2E', lineHeight: 14 },
  verticalSignatureName: { fontSize: 10, color: '#2B2B2B', marginBottom: 3, textAlign: 'center' },
  verticalSignatureLabel: { fontSize: 11, color: '#333333', textAlign: 'center' },
  flipHint: { fontSize: 11, color: '#6B7280', fontWeight: '600' },
  qrOuter: { padding: 6, backgroundColor: '#FFFFFF' },
  qrGrid: { borderWidth: 1, borderColor: '#111111' },
  qrRow: { flexDirection: 'row' },
  qrCell: { width: 4, height: 4 },
  qrCellDark: { backgroundColor: '#111111' },
  qrCellLight: { backgroundColor: '#FFFFFF' },
  headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 14, flexWrap: 'wrap', gap: 10 },
  pageTitle: { fontSize: 18, fontWeight: '800', color: '#151515', marginBottom: 2 },
  pageSubtitle: { fontSize: 12, color: '#2C2C2C', maxWidth: 400 },
  headerActions: { flexDirection: 'row', gap: 8 },
  backBtn: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 8, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#D1D5DB' },
  backBtnText: { fontSize: 12, color: '#374151', fontWeight: '600' },
  printBtn: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 8, backgroundColor: '#079B72' },
  printBtnDisabled: { backgroundColor: '#9CA3AF' },
  printBtnText: { fontSize: 12, color: '#FFFFFF', fontWeight: '700' },
  fichaTabsRow: { marginBottom: 8, maxHeight: 32 },
  fichaTabsContent: { gap: 8, paddingRight: 4 },
  fichaTab: {
    width: 82,
    height: 30,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#C7D7D0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fichaTabActive: { backgroundColor: '#087C4A', borderColor: '#087C4A' },
  fichaTabText: { fontSize: 12, lineHeight: 14, fontWeight: '800', color: '#3F4A45', textAlign: 'center' },
  fichaTabTextActive: { color: '#FFFFFF' },
  fichaInfo: { marginBottom: 10 },
  fichaInfoTitle: { fontSize: 15, fontWeight: '900', color: '#1F2937' },
  fichaInfoSub: { fontSize: 12, color: '#6B7280', marginTop: 2 },
  carnetGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 16 },
  fichaPrintGroup: { width: '100%', marginBottom: 18 },
  fichaPrintTitle: { fontSize: 14, fontWeight: '900', color: '#087C4A', marginBottom: 10 },
  emptyText: { color: '#9CA3AF', fontSize: 13, padding: 20 },
  carnetCard: {
    width: 300,
    borderRadius: 14,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.14,
    shadowRadius: 10,
    elevation: 6,
    backgroundColor: '#FFFFFF',
  },
  carnetHeader: { backgroundColor: '#079B72', flexDirection: 'row', alignItems: 'center', padding: 10, gap: 8 },
  carnetLogoBox: { width: 32, height: 32, borderRadius: 6, backgroundColor: '#FFFFFF', justifyContent: 'center', alignItems: 'center' },
  carnetLogoText: { fontSize: 9, fontWeight: '900', color: '#079B72' },
  carnetInstitution: { fontSize: 10, fontWeight: '800', color: '#FFFFFF' },
  carnetSubtitle: { fontSize: 8, color: '#D1FAE5' },
  carnetBody: { flexDirection: 'row', padding: 10, gap: 10 },
  carnetPhotoBox: {
    width: 74,
    height: 92,
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: '#E5E7EB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  carnetPhoto: { width: '100%', height: '100%' },
  carnetPhotoPlaceholder: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#D1FAE5',
  },
  carnetPhotoInitial: { fontSize: 28, fontWeight: '900', color: '#047857' },
  carnetData: { flex: 1, gap: 4 },
  carnetName: { fontSize: 13, fontWeight: '800', color: '#111827' },
  roleBadge: { alignSelf: 'flex-start', backgroundColor: '#E8FFF5', borderRadius: 999, paddingHorizontal: 8, paddingVertical: 3 },
  roleBadgeText: { fontSize: 9, fontWeight: '800', color: '#047857' },
  carnetFieldRow: { flexDirection: 'row', alignItems: 'center' },
  carnetFieldLabel: { fontSize: 9, fontWeight: '800', color: '#4B5563' },
  carnetFieldValue: { flex: 1, fontSize: 9, color: '#111827' },
  carnetFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
    paddingHorizontal: 10,
    paddingBottom: 10,
  },
  carnetFooterText: { fontSize: 8, color: '#6B7280', fontWeight: '700' },
});
