import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#EAE6E6' },
  contentFrame: { flex: 1, flexDirection: 'row' },
  mainArea: { flex: 1 },
  mainScroll: { flexGrow: 1, paddingTop: 6, paddingBottom: 24 },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(17, 24, 39, 0.54)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
  },
  modalPanel: {
    width: '100%',
    maxWidth: 380,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    padding: 14,
    gap: 12,
  },
  modalHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  modalTitleBlock: { flex: 1 },
  modalTitle: { fontSize: 15, fontWeight: '900', color: '#111827' },
  modalSubtitle: { fontSize: 12, fontWeight: '700', color: '#6B7280', marginTop: 2 },
  closeBtn: { paddingHorizontal: 12, paddingVertical: 7, borderRadius: 8, backgroundColor: '#F3F4F6' },
  closeBtnText: { fontSize: 12, fontWeight: '800', color: '#374151' },
  singlePrintArea: { alignItems: 'center', paddingVertical: 8 },
  modalActions: { alignItems: 'flex-end' },
  verticalCarnet: {
    width: 265,
    height: 420,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#C5C9C7',
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 12,
    justifyContent: 'space-between',
  },
  verticalTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    height: 140,
    paddingBottom: 4,
  },
  verticalLogoBox: { width: 72, alignItems: 'center' },
  verticalLogo: { width: 68, height: 68 },
  verticalPhotoFrame: {
    width: 108,
    height: 122,
    borderRadius: 6,
    overflow: 'hidden',
    backgroundColor: '#E5E7EB',
  },
  verticalPhoto: { width: '100%', height: '100%' },
  verticalBody: { marginTop: 10, flex: 1, justifyContent: 'flex-start' },
  verticalRole: {
    fontSize: 12,
    color: '#374151',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    fontWeight: '600',
    lineHeight: 14,
    marginBottom: 2,
  },
  verticalGreenRule: {
    height: 5,
    backgroundColor: '#00A74F',
    borderRadius: 0,
    marginBottom: 10,
  },
  verticalBrand: {
    fontSize: 18,
    lineHeight: 21,
    fontWeight: '800',
    color: '#0B7F35',
    marginBottom: 4,
  },
  verticalIdentity: { fontSize: 11.5, fontWeight: '600', color: '#374151', marginBottom: 10 },
  verticalBarcodeWrap: {
    height: 28,
    flexDirection: 'row',
    alignItems: 'flex-end',
    marginTop: 10,
    marginBottom: 6,
  },
  verticalBarcodeBar: { height: 26, backgroundColor: '#000000' },
  verticalFooter: { gap: 2, paddingBottom: 2 },
  verticalRegional: { color: '#374151', fontSize: 11, fontWeight: '700' },
  verticalCenter: { color: '#0B7F35', fontSize: 11, fontWeight: '700' },
  verticalMuted: { color: '#374151', fontSize: 11, fontWeight: '700' },
  verticalCarnetBack: { backgroundColor: '#FFFFFF', justifyContent: 'space-between' },
  verticalBackText: { fontSize: 9.5, color: '#374151', lineHeight: 14, fontWeight: '500' },
  verticalSignatureImage: { width: 160, height: 50, marginBottom: 3 },
  verticalSignatureLabel: { fontSize: 10, color: '#0B7F35', textAlign: 'center', fontWeight: '600' },
  flipHint: { fontSize: 11, color: '#6B7280', fontWeight: '600' },
  qrOuter: { padding: 6, backgroundColor: '#FFFFFF' },
  qrGrid: { borderWidth: 1, borderColor: '#111111' },
  qrRow: { flexDirection: 'row' },
  qrCell: { width: 4, height: 4 },
  qrCellDark: { backgroundColor: '#111111' },
  qrCellLight: { backgroundColor: '#FFFFFF' },
  headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 14, flexWrap: 'wrap', gap: 10 },
  pageTitle: { fontSize: 18, fontWeight: '800', color: '#151515', marginBottom: 2 },
  pageSubtitle: { fontSize: 12, color: '#2C2C2C', maxWidth: 400 },
  headerActions: { flexDirection: 'row', gap: 8 },
  backBtn: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 8, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#D1D5DB' },
  backBtnText: { fontSize: 12, color: '#374151', fontWeight: '600' },
  printBtn: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 8, backgroundColor: '#079B72' },
  printBtnDisabled: { backgroundColor: '#9CA3AF' },
  printBtnText: { fontSize: 12, color: '#FFFFFF', fontWeight: '700' },
  fichaTabsRow: { marginBottom: 8, maxHeight: 32 },
  fichaTabsContent: { gap: 8, paddingRight: 4 },
  fichaTab: {
    width: 82,
    height: 30,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#C7D7D0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fichaTabActive: { backgroundColor: '#087C4A', borderColor: '#087C4A' },
  fichaTabText: { fontSize: 12, lineHeight: 14, fontWeight: '800', color: '#3F4A45', textAlign: 'center' },
  fichaTabTextActive: { color: '#FFFFFF' },
  fichaInfo: { marginBottom: 10 },
  fichaInfoTitle: { fontSize: 15, fontWeight: '900', color: '#1F2937' },
  fichaInfoSub: { fontSize: 12, color: '#6B7280', marginTop: 2 },
  carnetGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 16 },
  fichaPrintGroup: { width: '100%', marginBottom: 18 },
  fichaPrintTitle: { fontSize: 14, fontWeight: '900', color: '#087C4A', marginBottom: 10 },
  emptyText: { color: '#9CA3AF', fontSize: 13, padding: 20 },
  carnetCard: {
    width: 300,
    borderRadius: 14,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.14,
    shadowRadius: 10,
    elevation: 6,
    backgroundColor: '#FFFFFF',
  },
  carnetHeader: { backgroundColor: '#079B72', flexDirection: 'row', alignItems: 'center', padding: 10, gap: 8 },
  carnetLogoBox: { width: 32, height: 32, borderRadius: 6, backgroundColor: '#FFFFFF', justifyContent: 'center', alignItems: 'center' },
  carnetLogoText: { fontSize: 9, fontWeight: '900', color: '#079B72' },
  carnetInstitution: { fontSize: 10, fontWeight: '800', color: '#FFFFFF' },
  carnetSubtitle: { fontSize: 8, color: '#D1FAE5' },
  carnetBody: { flexDirection: 'row', padding: 10, gap: 10 },
  carnetPhotoBox: {
    width: 74,
    height: 92,
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: '#E5E7EB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  carnetPhoto: { width: '100%', height: '100%' },
  carnetPhotoPlaceholder: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#D1FAE5',
  },
  carnetPhotoInitial: { fontSize: 28, fontWeight: '900', color: '#047857' },
  carnetData: { flex: 1, gap: 4 },
  carnetName: { fontSize: 13, fontWeight: '800', color: '#111827' },
  roleBadge: { alignSelf: 'flex-start', backgroundColor: '#E8FFF5', borderRadius: 999, paddingHorizontal: 8, paddingVertical: 3 },
  roleBadgeText: { fontSize: 9, fontWeight: '800', color: '#047857' },
  carnetFieldRow: { flexDirection: 'row', alignItems: 'center' },
  carnetFieldLabel: { fontSize: 9, fontWeight: '800', color: '#4B5563' },
  carnetFieldValue: { flex: 1, fontSize: 9, color: '#111827' },
  carnetFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
    paddingHorizontal: 10,
    paddingBottom: 10,
  },
  carnetFooterText: { fontSize: 8, color: '#6B7280', fontWeight: '700' },
});
