server:
  port: ${PORT:${SERVER_PORT:8080}}
  address: 0.0.0.0

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
              - HEAD
            allowedHeaders: "*"
            exposedHeaders: "*"
            allowCredentials: false
            maxAge: 3600
      routes:
        - id: options-preflight
          uri: ${USER_SERVICE_URI:http://localhost:9091}
          order: 0
          predicates:
            - Method=OPTIONS

        - id: uploads-routes
          uri: ${USER_SERVICE_URI:http://localhost:9091}
          order: 1
          predicates:
            - Path=/uploads/**

        # Rutas públicas de auth (sin JWT)
        - id: auth-public-routes
          uri: ${AUTH_SERVICE_URI:https://myaccess-auth-pzen.onrender.com}
          order: 2
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=2

        # Rutas protegidas de user-service
        - id: user-routes
          uri: ${USER_SERVICE_URI:https://myaccess-user.onrender.com}
          order: 3
          predicates:
            - Path=/api/v1/register/**
          filters:
            - JwtAuthFilter
            - StripPrefix=2

        # Rutas protegidas de card-service
        - id: card-routes
          uri: ${CARD_SERVICE_URI:https://myaccess-card-a4e6.onrender.com}
          order: 4
          predicates:
            - Path=/api/v1/cardService/**
          filters:
            - JwtAuthFilter
            - StripPrefix=2

        # Rutas protegidas de news-service
        - id: news-routes
          uri: ${NEWS_SERVICE_URI:https://myaccess-news-poqo.onrender.com}
          order: 5
          predicates:
            - Path=/api/v1/newsService/**
          filters:
            - JwtAuthFilter
            - StripPrefix=2

        # Rutas protegidas de notifications-service
        - id: notifications-routes
          uri: ${NOTIFICATIONS_SERVICE_URI:https://myaccess-notification-mjsk.onrender.com}
          order: 6
          predicates:
            - Path=/api/v1/notificationsService/**
          filters:
            - JwtAuthFilter
            - StripPrefix=2

security:
  jwt:
    secret-key: ${JWT_SECRET:alht7XYKujQPw1ourB0c4rIRg4x6RNrqewufShlZoug=}
