server:
  port: ${PORT:${SERVER_PORT:9091}}
  address: 0.0.0.0
  tomcat:
    max-part-count: 50

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: user-service
  datasource:
    user-service:
      jdbc-url: ${USER_DB_URL:jdbc:mysql://gateway01.us-east-1.prod.aws.tidbcloud.com:4000/user_service?sslMode=REQUIRED}
      username: ${DB_USERNAME:root}
      password: ${DB_PASSWORD:}
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        initialization-fail-timeout: 0
    auth-service:
      jdbc-url: ${AUTH_DB_URL:jdbc:mysql://gateway01.us-east-1.prod.aws.tidbcloud.com:4000/auth_service?sslMode=REQUIRED}
      username: ${DB_USERNAME:root}
      password: ${DB_PASSWORD:}
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        initialization-fail-timeout: 0
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 20MB

security:
  jwt:
    secret-key: ${JWT_SECRET:alht7XYKujQPw1ourB0c4rIRg4x6RNrqewufShlZoug=}
    tokenExpiration: ${JWT_EXPIRATION:600000}
    refreshTokenExpiration: ${JWT_REFRESH_EXPIRATION:600000}
